{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justscan.fullname" . }}-secrets
  labels:
    {{- include "justscan.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
  {{- if not .Values.postgresql.enabled }}
  db-password: {{ .Values.backend.secrets.dbPassword | quote }}
  {{- end }}
  encryption-key: {{ .Values.backend.secrets.encryptionKey | quote }}
  oidc-client-secret: {{ .Values.backend.secrets.oidcClientSecret | quote }}
  nvd-api-key: {{ .Values.backend.secrets.nvdApiKey | quote }}
{{- end }}
